# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftin', '0004_draft_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='draftin_user_email',
            field=models.EmailField(max_length=254),
        ),
    ]
