# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 20:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftin', '0008_auto_20160110_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='external_url',
            field=models.URLField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='draft',
            name='content',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='draft',
            name='content_html',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='draft',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='draft',
            name='draft_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='draftin_user_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='draft',
            name='name',
            field=models.CharField(max_length=512, verbose_name=b'Title'),
        ),
    ]
