# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-04 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draftin', '0009_auto_20160124_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='draft',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='draft',
            name='content_html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='draft',
            name='external_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='draft',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='draft',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='draftin.Publication', verbose_name='External Publication'),
        ),
    ]
