# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-05 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftin', '0010_auto_20160904_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='canonical_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='draft',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='draft_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
