# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-04 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftin', '0011_auto_20160905_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
