# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-17 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftin', '0012_draft_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='draftin/img/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional dek.'),
        ),
    ]
