# Generated by Django 2.0 on 2017-12-03 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draftin', '0013_auto_20161217_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='draftin.Publication', verbose_name='External Publication'),
        ),
    ]
